### ISSUE TITLE
Error with latest update

### ISSUE THREAD

**Issue by wburgers** [atomicptr/hoyo-daily-logins-helper#3]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/src/__main__.py", line 1, in <module>
    from src.main import main
  File "/app/src/main.py", line 7, in <module>
    from src._version import __version__
ModuleNotFoundError: No module named 'src._version'
```

**Comment by atomicptr** [comment]
Thanks for reporting, if this is from the Docker image I just pushed an update, if not you need to run "python -m build" first

**Comment by wburgers** [comment]
Sorry, forgot to mention that I used the docker container indeed.

It is now working perfectly again.
Thank you for creating this useful tool!
